import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Acceuil from '@/components/Accueil'
import SubHome from '@/components/Accueil/SubHome'
import ChefSection from '@/components/ChefSection'
import Contact from '@/components/Contact'
import About from '@/components/About'
import Gallery from '@/components/Gallery'
import Menu from '@/components/Menu'
import Footer from '@/components/Footer'

export default function Home({menu}) {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Acceuil />
        <SubHome />
        <ChefSection />
        <Menu menu={menu} />
        <Gallery />
        <About />
        <Contact />
        <Footer />
      </main>
    </>
  )
}

export async function getStaticProps(){

  const menu = await import(`./data/menu.json`);
  


  return {
    props: {
      menu: menu.menu,
    }
  }

}
